spring:
  application:
    name: '@project.artifactId@'
  main:
    banner-mode: "off"
  dbcp2:
    max-wait-millis: 30000
    validation-query: "SELECT 1"
    validation-query-timeout: 30
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: <issuer link>
springdoc:
  pathsToMatch: /api/**
logging:
  level:
    root: INFO

---
# DEV
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/kx-execution-dev?useSSL=false&allowPublicKeyRetrieval=true}
    username: ${JDBC_DATABASE_USERNAME:root}
    password: ${JDBC_DATABASE_PASSWORD:HaB4Wc-C8t3X-Bmk99}
    driver-class-name: com.mysql.jdbc.Driver
feign:
  url: <kx-blockchain-middleware url>
stage: dev

---
# local - deployed on AWS for dev
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${JDBC_DATABASE_URL:}
    username: ${JDBC_DATABASE_USERNAME:}
    password: ${JDBC_DATABASE_PASSWORD:}
feign:
  url: <kx-blockchain-middleware url>
stage: local

---
# testing - deployed on AWS
spring:
  config:
    activate:
      on-profile: testing
  datasource:
    url: ${JDBC_DATABASE_URL:}
    username: ${JDBC_DATABASE_USERNAME:}
    password: ${JDBC_DATABASE_PASSWORD:}
feign:
  url: <kx-blockchain-middleware url>
stage: testing

---
# test - deployed on AWS
spring:
  config:
    activate:
      on-profile: it
feign:
  url: <kx-blockchain-middleware url>
stage: it
